### ISSUE TITLE
Cut a new release for Rails 7.1?

### ISSUE THREAD

**Issue by geoffharcourt** [ankane/active_kms#2]
Hello!

Currently it appears that the old log styling syntax is resulting in a noisy deprecation warning about using a boolean vs. `bold: true` for bolding a log line. The code has already been fixed as of c2d825c7166231058c744bd04daf89b15f6e9d15, it's just not released yet. https://github.com/ankane/active_kms/blob/4f5545194b9cf5aa922bd56b11786f8e855ac6ec/lib/active_kms/log_subscriber.rb#L7

Could you cut a release with the change? Without it a frequent KMS-calling suite has a lot of this:

```
Bolding log text with a positional boolean is deprecated and will be removed 
in Rails 7.2. Use an option hash instead (eg. `color("my text", :red, bold: true)`).
```

**Comment by ankane** [comment]
Thanks @geoffharcourt, just pushed 0.1.1.

**Comment by geoffharcourt** [comment]
Always so fast! Thank you @ankane.
